### ISSUE TITLE
Cannot find JAVA_HOME even if exists

### ISSUE THREAD

**Issue by almogtavor** [DanySK/gradle-pre-commit-git-hooks#141]
### Was this something which used to work for you, and then stopped?

I never saw this working

### Describe the bug

Cannot commit and get the following message:
![image](https://user-images.githubusercontent.com/70065337/179367152-f9340800-c0a2-40e9-9259-5017e445a735.png)

But when I check in my cmd I do have JAVA_HOME specified. This means that the plugin prevents me from committing.

Also - I generally think that there's should be an option for enabling java based hooks. The cons of this are that they're very slow (makes my Gradle wrapper get initialized for a simple commit).

### Your configuration

Irrelvant

### Gradle build scan and relevant logs

Irrelvant

### Have you created a minimal reproduction repository?

No reproduction repository

**Comment by DanySK** [comment]
@almogtavor without a reproduction repository it is impossible for me to tackle this issue. I need to see what is the script being invoked. That looks like a Gradle error, and it looks like you have no `java` in your path, it does not look like a plugin problem.
What happens if you launch
`java -version`
from your terminal?

**Comment by almogtavor** [comment]
The error didn't happen since and I cannot reproduce it. I will re-open if that will ever happen again.
